import { Inter } from "next/font/google";
import "./globals.css";
import Navber from "@/Component/Navber_and_footer/Navber";
import Footer from "@/Component/Navber_and_footer/Footer"
import AuthProvider from "@/services/AuthProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Care doctore project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navber></Navber>
          {children}
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
